name: 'Check submodule against its repo'
description: 'Compare the hash of a linked submodule, to that of the main branch of its repository'
inputs:
  SUBMODULE_GIT_URL:  
    description: 'https://...(name).git for the repo targeted by submodule'
    required: true
  SUBMODULE_MAIN_BRANCH:  
    description: 'branch to check'
    required: true
    default: 'master'
  SLACK_WEBHOOK:  
    description: 'The slack webhook to use for alerting if we are behind'
    required: true
runs:
  using: "composite"
  steps:
    - run: sh ${{ github.action_path }}/check.sh
      env:
        SUBMODULE_GIT_URL: ${{ inputs.SUBMODULE_GIT_URL }}
        SUBMODULE_MAIN_BRANCH: ${{ inputs.SUBMODULE_MAIN_BRANCH }}
        NAME: ${{ github.repository }}
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
        WORKSPACE: ${{github.workspace}}

      shell: bash